import { Post, User } from './types';

export const CURRENT_USER: User = {
  id: 'u_me',
  username: 'spark_creator',
  name: 'Alex Spark',
  avatar: 'https://picsum.photos/id/64/200/200',
  bio: 'Chasing lights and pixels ⚡️',
  accountType: 'personal',
  category: 'Digital Creator',
  followers: 9500000, // Close to 10M for testing
  verificationType: 'none',
  verificationStatus: 'none',
  isAdmin: false,
  walletBalance: 0,
  totalEarnings: 0,
};

export const ADMIN_USER: User = {
  id: 'u_admin',
  username: 'admin',
  name: 'Instant Spark Admin',
  avatar: 'https://ui-avatars.com/api/?name=Admin&background=0D8ABC&color=fff',
  bio: 'Platform Administrator',
  accountType: 'professional',
  followers: 0,
  verificationType: 'blue',
  verificationStatus: 'approved',
  isAdmin: true,
  walletBalance: 0, // Admin wallet holds the 25% cut
  totalEarnings: 0,
};

export const MOCK_USERS: User[] = [
  { 
    id: 'u1', 
    username: 'wanderlust_jen', 
    name: 'Jen Travels', 
    avatar: 'https://picsum.photos/id/1011/200/200',
    accountType: 'professional',
    category: 'Travel Blogger',
    followers: 12500,
    verificationType: 'black',
    verificationStatus: 'approved',
    walletBalance: 0,
    totalEarnings: 0,
  },
  { 
    id: 'u2', 
    username: 'tech_guru_mike', 
    name: 'Mike Codes', 
    avatar: 'https://picsum.photos/id/1005/200/200',
    accountType: 'personal',
    followers: 500,
    verificationType: 'none',
    verificationStatus: 'none',
    walletBalance: 0,
    totalEarnings: 0,
  },
  { 
    id: 'u3', 
    username: 'mega_star_sam', 
    name: 'Sam Superstar', 
    avatar: 'https://picsum.photos/id/1027/200/200',
    accountType: 'professional',
    category: 'Celebrity',
    followers: 12000000,
    verificationType: 'golden',
    verificationStatus: 'approved',
    walletBalance: 5400,
    totalEarnings: 12500,
  },
];

export const MOCK_POSTS: Post[] = [
  {
    id: 'p1',
    type: 'image',
    url: 'https://picsum.photos/id/28/1080/1080',
    user: MOCK_USERS[0],
    caption: 'Lost in the woods, but found myself. 🌲✨ #Nature #Vibes',
    likes: 124,
    views: 1500,
    comments: [],
    timestamp: Date.now() - 3600000,
    isLiked: false,
  },
  {
    id: 'p2',
    type: 'image',
    url: 'https://picsum.photos/id/48/1080/1350',
    user: MOCK_USERS[1],
    caption: 'Coding late night. The grind never stops! 💻☕️ #Developer #InstantSpark',
    likes: 89,
    views: 400,
    comments: [],
    timestamp: Date.now() - 7200000,
    isLiked: true,
  },
  {
    id: 'p3',
    type: 'video',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    user: MOCK_USERS[2],
    caption: 'Weekend drive vibes! 🚗💨 #Roadtrip',
    likes: 45000,
    views: 2500000,
    comments: [],
    timestamp: Date.now() - 10800000,
    isLiked: false,
  },
];

export const MOCK_REELS: Post[] = [
  {
    id: 'r1',
    type: 'video',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    user: MOCK_USERS[1],
    caption: 'When the code finally works... 😂 #DevLife #Reels',
    likes: 1205,
    views: 5600,
    comments: [],
    timestamp: Date.now(),
  },
  {
    id: 'r2',
    type: 'video',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    user: MOCK_USERS[0],
    caption: 'Escape the ordinary. 🌍 #Travel',
    likes: 850,
    views: 3200,
    comments: [],
    timestamp: Date.now(),
  },
   {
    id: 'r3',
    type: 'video',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    user: MOCK_USERS[2],
    caption: 'Wait for it... 🐘 #Wild',
    likes: 300000,
    views: 15000000,
    comments: [],
    timestamp: Date.now(),
  },
];